# Generated by Django 5.2.7 on 2025-11-19 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('profile', models.ImageField(default='profile/default.jpg', upload_to='profile/')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
