# Generated by Django 5.2.7 on 2025-11-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_admin_customer_seller_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
