# Generated by Django 5.2.7 on 2025-11-19 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('quantity', models.PositiveIntegerField()),
                ('number', models.UUIDField(blank=True, default=uuid.UUID('9c888282-97d7-4118-9c45-315a62bf0d2b'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('On Delivery', 'On Delivery')], default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Out of Stocks', 'Out Of Stock')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StatusofDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.UUIDField(blank=True, default=uuid.UUID('5acc63bb-7546-4419-bf89-0da47017f8df'), primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('On Delivery', 'On Delivery')], default='Pending', max_length=30)),
                ('order_item', models.ManyToManyField(to='products.orderitem')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.products'),
        ),
    ]
