# Generated by Django 5.2.7 on 2025-11-19 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash on Delivery', 'Cod'), ('Pay Maya', 'Maya'), ('G-Cash', 'G Cash'), ('B.P.I', 'Bpi'), ('Go Tyme', 'Go Tyme'), ('Others', 'Others')], default='Cash on Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('27ca3ad4-53ee-4c9e-904e-732daa83b16e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('8e3ae824-8223-4c10-80ec-76cd23a1fc7f'), primary_key=True, serialize=False),
        ),
    ]
