# Generated by Django 5.2.5 on 2025-12-01 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='StatusofDelivery',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash on Delivery', 'Cod'), ('Pay Maya', 'Maya'), ('G-Cash', 'G Cash'), ('B.P.I', 'Bpi'), ('Go Tyme', 'Go Tyme'), ('Others', 'Others')], default='Cash on Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_discount_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
