# Generated by Django 5.2.7 on 2025-11-19 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_payment_order_payment_alter_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('b074c2c1-7008-4f41-9d80-af34b33751b7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('72e0a8fd-2c1f-44c5-96a2-e1d40e0a36ba'), primary_key=True, serialize=False),
        ),
    ]
