# Generated by Django 5.2.7 on 2025-11-19 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_image_alter_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('fa84d16c-19ff-4669-b9ab-a2138fea2565'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('4928ceee-2aa1-469d-bfbb-8b3232694354'), primary_key=True, serialize=False),
        ),
    ]
