# Generated by Django 5.2.7 on 2025-11-21 00:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_number_alter_orderitem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('0b51587f-b166-4c31-a2e0-e09ee85d76be'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('7720810b-d46c-4bbb-92e1-d0d08ebbdbe2'), primary_key=True, serialize=False),
        ),
    ]
