# Generated by Django 5.2.7 on 2025-11-21 00:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_number_alter_orderitem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('e801ecf0-4e52-4e89-8187-f51fcf136bd0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('d7629794-ad9b-4ead-be1e-5c451fce11f7'), primary_key=True, serialize=False),
        ),
    ]
