# Generated by Django 5.2.7 on 2025-11-21 00:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_number_alter_orderitem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('ec09e979-8523-42fc-99aa-bcced56a2674'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('90b09d7c-4283-42ee-b575-5ea810be2ba1'), primary_key=True, serialize=False),
        ),
    ]
