# Generated by Django 5.2.7 on 2025-11-24 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_number_alter_orderitem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('ae00371c-ede1-49b2-9c56-14c0988f4886'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='number',
            field=models.UUIDField(blank=True, default=uuid.UUID('e3806f21-abd5-45ac-a399-3fbae87b3dc5'), primary_key=True, serialize=False),
        ),
    ]
